### ISSUE TITLE
iCloud Sync is broken (Account Setup: 401 Error)

### ISSUE THREAD

**Issue by ben-8409** [bitfireAT/davdroid#145]
I wanted to use DAVdroid (which works fine for other services for me) to sync my iCloud Contacts. But i get a 401: Unauthorized in Account setup. Same settings and login details work with CardDav Sync.

**Comment by flaxton** [comment]
OK, I determined (not by the above method - there is no such "Share" button) by looking at the ~/Library/Preferences/MobileMeAccounts.plist file that I am using server p02, so I tried Base URL: https://p02-contacts.icloud.com and still get "HTTP error: 401 Unauthorized"...

**Comment by flaxton** [comment]
Uninstalled and did a refund, unless I hear an answer. Not everyone is familiar with Github - you should really have a support forum!

**Comment by rfc2822** [comment]
@flaxton These instructions are not applicable anymore.

Just use icloud.com as domain, as described on https://davdroid.bitfire.at/configuration. Did you use the configuration mentioned there?:

Email: youraccount@icloud.com
Non-@icloud.com accounts: https:// icloud.com

> Uninstalled and did a refund, unless I hear an answer. Not everyone is familiar with Github - you should really have a support forum!

We consider payments in commercial stores as donations for the open-source software DAVdroid as you may also download the APK directly from Github or F-droid without paying anything.

**Comment by flaxton** [comment]
Thank you for getting back to me.

OK, I think the problem occurred when I had enabled Apple two-factor authentication some time ago.

I had been using iCloud Sync for Android, and then found it had not synced in more than a month. It did not immediately occur to me that it could be Apple iCloud two-factor authentication that had changed, since it had been some time since I had turned it on (probably the last successful sync, now that I look at it). That is what led me to try DAVdroid - I just thought that the iCloud Sync for Android had updated and broken itself.

I turned iCloud two-factor authentication off and then iCloud Sync for Android worked, where it was getting the same error message as DAVdroid before. So I did not go any further, as that was what led me to DAVdroid in the first place.

You might want to turn on iCloud two-factor authentication and see if DAVdroid works with it on. I bet it won’t.

Thanks!

Fred


—

 <http://infotechdesign.net/>
Fred Laxton / Web Designer, Internet Marketer 
fred@infotechdesign.net <mailto:fred@infotechdesign.net> / 864-724-9112

InfoTechDesign LLC 
Mailing Address:
2435 E North St, #303 Greenville, SC 29615 
http://infotechdesign.net <http://infotechdesign.net/>
  <https://twitter.com/fredonline> <http://linkedin.com/in/fredonline>
 <http://www.amazon.com/Intro-using-Social-Business--mouth-ebook/dp/B00MKC81MU/ref=sr_1_1?ie=UTF8&qid=1424269959&sr=8-1&keywords=intro+to+using+social+media+for+business>

**Comment by rfc2822** [comment]
Thanks for the information. I'll close this issue now because the problem seems to be resolved.
