### ISSUE TITLE
[Davical] Couldn't parse Multi-Status response on REPORT multi-get

### ISSUE THREAD

**Issue by bestouff** [bitfireAT/davdroid#441]
It happens sometimes at boot, with a Davical server. I don't know how to reproduce it so I can't deliver a true logcat, sorry.

**Comment by bestouff** [comment]
Here is the notification of the failure:

![tmp_3357-screenshot_2015-02-11-15-19-07-392496953](https://cloud.githubusercontent.com/assets/1163188/6148491/3361a698-b202-11e4-808c-8ba85832ba97.png)

**Comment by rfc2822** [comment]
I'm sorry, without more information, I can't do anything.

Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

Can you provide a DAViCal test account? There seem to be many problems with it, but we can't test against it because we don't have a Davical account.

**Comment by bestouff** [comment]
I can do that, but only in private of course.

**Comment by rfc2822** [comment]
@bestouff Please send it to play@bitfire.at (PGP [0B2B4566](https://davdroid.bitfire.at/0B2B4566.asc)). It would be helpful if you could keep it online until we have investigated. I don't know how long it will take (few days to a few weeks, I guess).

**Comment by bestouff** [comment]
Done, look at mail from xavier.bestel@free.fr.

**Comment by rfc2822** [comment]
Thanks, I have received the account and added it successfully. I have also added two contacts and multi-get seems to work.

Can you please add contacts, events or whatever so that the test account throws the given error? Then I can have a look at the cause.

**Comment by rfc2822** [comment]
Any news on this?
