### ISSUE TITLE
No error messages at sync

### ISSUE THREAD

**Issue by thedd** [bitfireAT/davdroid#447]
I have changed my SSL certificate (without adding it to the device again) and there was no error message that the sync failed. It just said that the last sync was a few days ago. So davdroid couldn't sync, but it didn't tell me. It would be nice if there's some kind of error message (notification?) when the sync encounters an error.

**Comment by rfc2822** [comment]
> It would be nice if there's some kind of error message (notification?) when the sync encounters an error.

The problem is that I/O error messages are mostly soft errors (i.e. they will occur, for instance when mobile network is dropping, but the attempt to sync will be repated and they're not permanent errors). DAVdroid can't know whether this is a permanent issue or whether its temporary.

However, I agree that certificate errors should be counted as hard errors (which will be shown).
