### ISSUE TITLE
Default fields for new contacts

### ISSUE THREAD

**Issue by Ede123** [bitfireAT/davdroid#493]
The fields initially shown when creating a contact should either be
* configurable by the user or
* pre-selected reasonably

Right now when adding a new contact I get the fields "Name", "Last name (phonetic)", "Middle Name (phonetic)", "First Name (phonetic)"... Personally I use neither of them!
I'd need "First Name" and "Last Name" and nothing else. Those are hidden behind an arrow though, requiring an additional tap, and with all the fields expanded the screen gets totally cluttered making yet again difficult to fill in the actual contact detail fields afterwards.

**Comment by rfc2822** [comment]
This is not unter control of DAVdroid, but your Contacts app (see https://twitter.com/davdroidapp/status/527057795980754945). Please report this to the vendor of your Contacts app.

**Comment by Ede123** [comment]
OK, thanks for clarification.

The fields shown are changing depending on the sync provider I select (e.g. Phone-Contact and Google-Contact show the same subset of fields while DAVDroid shows a lot more), so I assumed the sync provider hints the Contacts app on which default fields to show.

If that's not the case I'll try to report it elsewhere.

**Comment by rfc2822** [comment]
> I assumed the sync provider hints the Contacts app on which default fields to show.

The sync provider can indeed tell the Contacts app which fields it does sync, so that the Contacts app doesn't even show unsynced fields (extreme case: read-only sync adapters like a so-called Facebook which provide no fields to edit).

However, it doesn't provide default values and has no influence on further Contacts app behaviour.

Maybe you can find a contacts editor that better matches your needs :) There are different ones out there.
