### ISSUE TITLE
Creation of accounts enhancement

### ISSUE THREAD

**Issue by kallegit1950** [bitfireAT/davdroid#571]
Hi,

today you have a radio button and you can select to create an account via email address or with URL and user name. I think Owncloud is more and more common and the URL for owncloud has always the same structure. So the question would be if it is possible to have a 3rd button to add an owncloud account (and possibly other common servers). I would be willing to look into the coding and provide a patch. I cannot promise that it is done in a day or two, but I am willing to do it. I would be only willing to do so if such patches get accepted (if quality of code is good of course) or if you don't accept things like these for various reasons.

Regards, K.

**Comment by untitaker** [comment]
Similar to https://github.com/bitfireAT/davdroid/issues/465, the proposal there is more generic but not as intuitive as your UI idea.

**Comment by kallegit1950** [comment]
Thanks for the link. Yes I guess that this issue would be solved as well with my proposal. I would have on my screen just fields for user, password, http/https, hostname, so minimum typing on a mobile device.

**Comment by rfc2822** [comment]
> So the question would be if it is possible to have a 3rd button to add an owncloud account (and possibly other common servers).

DAVdroid uses well-known URLs for that, see https://davdroid.bitfire.at/configuration

These URLs can be configured for any service and OwnCloud even gives an example in the manual. When you're using them, there's no need for clients like DAVdroid to know implementation-specific details.

**Comment by kallegit1950** [comment]
Of course these URLs are "well known" (to you and me). For non tech-savy people it might be a different story. Apart from that, comfort would be much increased if you don't have to lookup these URLs and type in by hand (on a tiny smartphone!) something like https://demo.ownlcoud.org/remote.php/caldav/calendars/demo/personal. So why not giving users this extra comfort? Does your answer mean you would decline a pull request if I provide this?

**Comment by rfc2822** [comment]
> Of course these URLs are "well known" (to you and me). For non tech-savy people it might be a different story.

If you're able to set up your own OwnCloud instance, you're also able to set up well-known URLs. They're just a redirection, this is one or two lines in your Web server config and it's even mentioned in the OwnCloud docs.

> Apart from that, comfort would be much increased if you don't have to lookup these URLs and type in by hand (on a tiny smartphone!) something like https://demo.ownlcoud.org/remote.php/caldav/calendars/demo/personal.

With well-known URLs, you only have to enter your host name.

You may also use the "Login with email" option: DAVdroid will then detect the host name from the email address domain and use the email address as user name.

> So why not giving users this extra comfort? Does your answer mean you would decline a pull request if I provide this?

DAVdroid won't use provider-specific settings. That would mean to have a database of providers and URLs and keep it up-to-date. Also, it's an error-prone approach because who says that you can't have a prefix for your OwnCloud installation or rename `remote.php` and what to do when the next OwnCloud version uses another path? Also, there are hundreds of different servers and services and keeping an up-to-date "path database" would be a very time consuming task.

I think the solution for dealing with complicated paths is support of well-known paths, so please don't submit a pull request for that.

**Comment by untitaker** [comment]
>Of course these URLs are "well known" (to you and me)

For clarification, ["well-known URIs"](https://tools.ietf.org/html/rfc5785) are a protocol DavDroid uses to detect the full DAV URL when only a hostname is given.
