### ISSUE TITLE
Avoid using @ in UIDs?

### ISSUE THREAD

**Issue by untitaker** [bitfireAT/davdroid#585]
I am not sure if it's either DavDroid or dmfs Tasks creating UIDs, but either way, I'd like it if DavDroid could replace unsafe UIDs such as the ones containing `@` with something that only contains alphanumeric chars and dashes. This will help working around URL-encoding bugs like https://github.com/owncloud/contacts/issues/581, I believe.

**Comment by rfc2822** [comment]
I guess you suggest this only for new resources, as existing UIDs must not be changed?

Also, I don't think this would be very helpful. Maybe it reduces the number of users who experience problems, but the problem will still exist. It may even be counterproductive because server problems are less likely to be fixed when only a small number of users experience them.

**Comment by untitaker** [comment]
Then why isn't it fixed? I reported it!

Your stance on reporting bugs to upstream is novel and I agree with it, but I
don't think you should challenge the stability of software in real-world usage.
That's what testsuites are for.

**Comment by rfc2822** [comment]
> Then why isn't it fixed? I reported it!

Guess it will be :) If nobody else is doing it, maybe I can, but not at the moment.

> I don't think you should challenge the stability of software in real-world usage.

For this reason, DAVdroid actually [generates iCals with "@" in the UID, but a file name where the "@" is replaced by "_"](https://github.com/bitfireAT/davdroid/blob/92966a5c570a60f1c9c330c9f2bf0ae57481d12d/app/src/main/java/at/bitfire/davdroid/resource/Event.java#L122). Maybe this approach would be useful for [Contacts](https://github.com/bitfireAT/davdroid/blob/92966a5c570a60f1c9c330c9f2bf0ae57481d12d/app/src/main/java/at/bitfire/davdroid/resource/Contact.java#L131) and [Tasks](https://github.com/bitfireAT/davdroid/blob/92966a5c570a60f1c9c330c9f2bf0ae57481d12d/app/src/main/java/at/bitfire/davdroid/resource/Task.java#L83), too.

However, there are other servers (Zimbra as far as I remember) which don't accept file names that are not the same as the UID and will redirect accordingly.

Maybe new UIDs should be really generated without @ too, or at least Contacts and Tasks should have file names where the "@" is replaced by "_" too.

On the other side, people will still report strange problems from time to time nevertheless until the problem is fixed upstream.

**Comment by untitaker** [comment]
I agree with everything you say.

>If nobody else is doing it, maybe I can, but not at the moment.

I'm trying to, see https://github.com/owncloud/contacts/pull/1003 I've also asked in IRC for help but no response so far.

>However, there are other servers (Zimbra as far as I remember) which don't accept file names that are not the same as the UID and will redirect accordingly.

That is interesting. Did you test this or is this from user reports?

**Comment by rfc2822** [comment]
> That is interesting. Did you test this or is this from user reports?

I have tested it myself. You can see a log in #156.

**Comment by rfc2822** [comment]
I will change the logic so that DAVdroid creates UIDs with "_" instead of "@", and file names according to the UID. This should minimize potential problems.

**Comment by untitaker** [comment]
Excellent, thanks!

On 28 July 2015 15:31:35 CEST, rfc2822 <notifications@github.com> wrote:
>Closed #585 via 243483a957a59e77861b324d7fc007f6abc6bb4d.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/585#event-367223010

-- 
Sent from my phone. Please excuse my brevity.
