### ISSUE TITLE
Socket is closed

### ISSUE THREAD

**Issue by andreicristianpetcu** [bitfireAT/davdroid#607]
Hello,

I get a "socket is closed" error. Here is the [log](https://gist.github.com/andreicristianpetcu/830719ab01743e294569)
I can provide a url, user and password for testing on my server just ask for it on `andreip` at the mail server `tuta.io` (I cannot post these credentials on github so please ask them on email). I can also provide the full log by email.

DavDroid version is 0.8.1 from F-Droid while ownCloud is 8.0.2 from owncube.com

Thank you!

**Comment by andreicristianpetcu** [comment]
Also check out [this](https://gist.github.com/andreicristianpetcu/9c537190a279d68aa048) log. This one has an exception also.

**Comment by devvv4ever** [comment]
On the first look it seems like a privacy guard or firewall setting is causing this...

**Comment by andreicristianpetcu** [comment]
@devvv4ever thank you for taking a look at this.
I do not have any privacy guard apps installed, I phone is not rooted. It used to work, I deleted and recreated the DavDroid account since it did not pick up new calendars. After I recreated it it stopped working.

The OwnCloud client on my Android, Gnome Calendar and Gnome Contacts can connect to the ownCloud instance. It does not seem to be a problem with the Android OS or with the server.

How can I get more information from this? As I said, I can give you the full log and an account on my server.

**Comment by devvv4ever** [comment]
You write additional private information to play@bitfire.at if you want...

**Comment by andreicristianpetcu** [comment]
thank you @devvv4ever I sent it.

**Comment by devvv4ever** [comment]
thanks, we will have a look at it in the next days!

**Comment by andreicristianpetcu** [comment]
I will donate some money to DavDroid in September :D

**Comment by rfc2822** [comment]
Same problem as #610: There's a SRV records that points to a service that doesn't respond.

```
$ host -t SRV _carddavs._tcp.andrei.owncube.com
_carddavs._tcp.andrei.owncube.com has SRV record 0 0 2080 ocshared-de18.owncube.com.
$ nc ocshared-de18.owncube.com 2080
Ncat: Connection timed out.
```

Please contact your hoster and include this issue's URL.

I'll close the issue for now because it's not a DAVdroid problem. If there's anything new, please feel free to post again nevertheless.

**Comment by andreicristianpetcu** [comment]
Ok. Thank you! I made an issue on ownCube. I will post here if the issue was fixed from their side.

**Comment by andreicristianpetcu** [comment]
from ownCube: "Our techs have looked into this already and there is no server side issue at all.
Also someone posted that they have issues with hosting provider Arvixe, so would be a wonder that ALL hosting providers have wrong server config right :)

The problem is that app that it takes the server hostname sft instead of the domain name that is configured in the SRV record or something, not sure how it is developed.

To verify our techs have tried other sync apps like caldavsync and carddavsync from the APP store and there is no issue at all, it uses right domain and connection and works instant, also with your provided testaccount so it could not be a server side issue at all or how can you/they explain that ALL other tested apps works ?!, its specified to this app that you can verify with EVERY other sync app in the app store and you will see it works fine, just this ONE app does not due reasons we dont understand.
Our techs will have a look anyway but because 4 different other cal/carddav apps are working fine we thinkg we dont investigate much time in this.
i will update you if i have more infos."

**Comment by devvv4ever** [comment]
Thanks for submitting a bug report there and following up here. 

This answer makes me lough a bit, since it is actually working with ALL other providers except OwnCube and Arvixxe – and there are MANY of them, really. 

Also, testing X different apps and saying that it must be a client issue if one client is not working is not an answer of an engineer or technican. It seems they didn't even take a look at issue #610 nor did they try to paste the terminal lines into a console mentioned there. You can easily try this _without_ even launching DAVdroid - you only need to test the connection paths with "host" and "nc". There you see that the connection times out, which sholdn't be.

DAVdroid is preferring SRV records over other mechanics. If they disable them (if they cannot set them up correctly without a timeout...) it should work too.

**Comment by andreicristianpetcu** [comment]
I gave them the link to the other issue.
"if you test ANY other app like cal carddav official from playstore or Thunderbird on any os also ios With integrated cal carddav function you will see it works perfect so obly davdroid dobt work.
we will check this of course but because ONLY davdroid does not work that you can verify with every other app it has low prio and we dont changr Server settings only because ONE app does use other development than all others.
i will update you if there are news."

Please tell me what API's you are using. Is there a ownCube instance that provides these API's and they are configured how DavDroid expects them?

Thank you. Sorry for this whole hassle :( I really want my issue fixed.

**Comment by devvv4ever** [comment]
I see 4 possible solutions:

1.) OwnCube needs to adjust their SRV records, then DAVdroid can find your paths
2.) OwnCube can delete the SRV records on the server, because they don't work anyway. Then DAVdroid checks other paths and it will most likely work.
3.) DAVdroid could be adapted to try another method after it gets a "socket closed / server timeout". However this is some kind of workaround, because we assume, if some service provider is using SRV records, that they know what they do. This will most likely not happen in the near future however...
4.) Using other great apps if they work is also a solution. This won't help the general but at least it helps you...

**Comment by andreicristianpetcu** [comment]
I tried other apps, they are not as good as DavDroid :)
I told them to remove their SRV records.
Can you please try also 3) on your side also? I might not be the only one that will go trough this problem and you might get rid of future duplicate bug reports in the future if you try solution 3).

**Comment by devvv4ever** [comment]
Thanks ;)

Yes, we will try it to add this feature, but as said, we don't know when...
